version: "3.8"

services:
  oficina:
    image: oficina:latest
    ports:
      - "8090:8000"
      - "4433:8000"
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: defina_uma_senha
      ADMIN_TOKEN: static-admin-token
      DEMO_USER: demo
      DEMO_PASSWORD: demo123
      DEMO_TOKEN: static-demo-token
      DATABASE_URL: sqlite:///./oficina.db
    volumes:
      - oficina_db:/app/backend/oficina.db
      - oficina_uploads:/app/backend/app/uploads
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  oficina_db:
  oficina_uploads:
